### PR TITLE
Update adr-template.md

### PR DESCRIPTION
**Pull request by azarboon**
Added a new field about measurement of results. This one should be optional (please make it, if it's not optional). Got the idea from the Mark Richard's video: https://www.youtube.com/watch?v=LMBqGPLvonU

I put the field in metadata section but I'm not religious about it.

### CODE REVIEW

**Comment by koppor** [comment]
> Added a new field about measurement of results.

There can be a long debate whether this field is meta data or integral part of the ADR. For me, it is part of the ADR. 

First this kind of thing appeared as "Validation" in the template - https://github.com/adr/madr/commit/02d9ed328cf6d258497ea6aa862f1eb631804033 - Kudos to @ungerts 

Then, we updated it to "Confirmation" (see https://github.com/adr/madr/pull/87)

In your proposed attribute, you use "compliance", which is in the description of "Confirmation":

image

We opted for "Confirmation", because it is more higher level than "Compliance". Some more inputs is brought in [ADR-0018](https://github.com/adr/madr/blob/develop/docs/decisions/0018-use-confirmation-as-heading.md).

Does this also cover your use case or do you miss something?

Should we refine `ADR-0018` to include `"Compliance Check"` as non-chosen option?

**Comment by azarboon** [comment]
> > Added a new field about measurement of results.
> 
> There can be a long debate whether this field is meta data or integral part of the ADR. For me, it is part of the ADR.
> 
> First this kind of thing appeared as "Validation" in the template - [02d9ed3](https://github.com/adr/madr/commit/02d9ed328cf6d258497ea6aa862f1eb631804033) - Kudos to @ungerts
> 
> Then, we updated it to "Confirmation" (see #87)
> 
> In your proposed attribute, you use "compliance", which is in the description of "Confirmation":
> 
> image
> 
> We opted for "Confirmation", because it is more higher level than "Compliance". Some more inputs is brought in [ADR-0018](https://github.com/adr/madr/blob/develop/docs/decisions/0018-use-confirmation-as-heading.md).
> 
> Does this also cover your use case or do you miss something?
> 
> Should we refine `ADR-0018` to include `"Compliance Check"` as non-chosen option?

Make sense. We can revise the "confirmation" section to include "fitness function". BTW, I think I've found a mistake. I asked Perplexity AI and seems I was correct:

Over there it's written "Describe how the compliance with the ADR will be confirmed." According to Perplexity AI:
_This implies that you are asking how adherence to the ADR's guidelines or requirements will be verified._
I think we should change it to "Describe how the compliance of the ADR will be confirmed." Because _This suggests that you are asking about the ADR itself being compliant._ What's your advice?

**Comment by koppor** [comment]
@atarigui May I ping you? We had fruitful wording discussions at https://github.com/adr/adr-manager/issues/155.

**Comment by atarigui** [comment]
I support the renaming to "Confirmation" as well as the proposal from @azarboon to use this descriptive text: "Describe how the compliance **of** the ADR will be confirmed."

**Comment by azarboon** [comment]
@koppor  I incorporated my change under "confirmation" part and also modified that typo part. Please let me know if there is anything else.

**Review by socadk — APPROVED** [review]

**Review by koppor — APPROVED** [review]

**Pull request merged**
